version: '3.1'

services:
  db:
    container_name: "mysql-5.5-redmine"
    image: mysql:5.5
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
    volumes:
     # MySQL configuration overrides
     # - "./.docker/etc/mysql/my.cnf:/etc/mysql/conf.d/z_my.cnf"
     # Permanent DB data storage
    - ./save-data/mysql:/var/lib/mysql
